CREATE DATABASE customer_churn;
USE customer_churn;
SELECT DATABASE();


-- Find the total number of customers

SELECT COUNT(*) AS total_customers
FROM customer_churn_clean;

--  Count customers who churned and did not churn
SELECT churn, COUNT(*) AS customer_count
FROM customer_churn_clean
GROUP BY churn;

-- Calculate the percentage of customers in each churn category
SELECT
    Churn,
    COUNT(*) AS customer_count,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM customer_churn_clean), 2) AS churn_percentage
FROM customer_churn_clean
GROUP BY Churn;

-- Find which churn category has the highest number of customers

SELECT
    Churn,
    COUNT(*) AS customer_count
FROM customer_churn_clean
GROUP BY Churn
ORDER BY customer_count DESC;

-- Count customers for each contract type

SELECT
    Contract,
    COUNT(*) AS customer_count
FROM customer_churn_clean
GROUP BY Contract
ORDER BY customer_count DESC;

-- Find how many customers churned under each contract type

SELECT
    Contract,
    Churn,
    COUNT(*) AS customer_count
FROM customer_churn_clean
GROUP BY Contract, Churn
ORDER BY Contract, customer_count DESC;

-- Calculate churn percentage for each contract type

SELECT
    Contract,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*),
        2
    ) AS churn_rate
FROM customer_churn_clean
GROUP BY Contract
ORDER BY churn_rate DESC;

-- Show only contract types having churn rate above 20%

SELECT
    Contract,
    ROUND(
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*),
        2
    ) AS churn_rate
FROM customer_churn_clean
GROUP BY Contract
HAVING churn_rate > 20
ORDER BY churn_rate DESC;

-- Count customers in each internet service category

SELECT
    InternetService,
    COUNT(*) AS customer_count
FROM customer_churn_clean
GROUP BY InternetService
ORDER BY customer_count DESC;

-- Compare churned and non-churned customers for each internet service

SELECT
    InternetService,
    Churn,
    COUNT(*) AS customer_count
FROM customer_churn_clean
GROUP BY InternetService, Churn
ORDER BY InternetService, customer_count DESC;

-- Calculate churn rate for each internet service

SELECT
    InternetService,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*),
        2
    ) AS churn_rate
FROM customer_churn_clean
GROUP BY InternetService
ORDER BY churn_rate DESC;

-- Find churn rate for each payment method

SELECT
    PaymentMethod,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*),
        2
    ) AS churn_rate
FROM customer_churn_clean
GROUP BY PaymentMethod
ORDER BY churn_rate DESC;

--  Show payment methods with churn rate above 25%

SELECT
    PaymentMethod,
    ROUND(
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*),
        2
    ) AS churn_rate
FROM customer_churn_clean
GROUP BY PaymentMethod
HAVING churn_rate > 25
ORDER BY churn_rate DESC;

-- Find the number of senior citizen customers

SELECT
    COUNT(*) AS senior_citizen_count
FROM customer_churn_clean
WHERE SeniorCitizen = 1;

-- Find the average monthly charge paid by churned customers

SELECT
    ROUND(AVG(MonthlyCharges), 2) AS avg_monthly_charge
FROM customer_churn_clean
WHERE Churn = 'Yes';

-- Find the total charges generated by churned customers

SELECT
    ROUND(SUM(TotalCharges), 2) AS total_charges
FROM customer_churn_clean
WHERE Churn = 'Yes';

-- Find the highest monthly charge among churned customers

SELECT
    MAX(MonthlyCharges) AS highest_monthly_charge
FROM customer_churn_clean
WHERE Churn = 'Yes';

-- Find customers whose MonthlyCharges are above the overall average

SELECT
    customerID,
    MonthlyCharges,
    Churn
FROM customer_churn_clean
WHERE MonthlyCharges > (
    SELECT AVG(MonthlyCharges)
    FROM customer_churn_clean
);

-- Find churned customers paying above the overall average monthly charge

SELECT
    customerID,
    MonthlyCharges,
    Contract,
    Churn
FROM customer_churn_clean
WHERE Churn = 'Yes'
  AND MonthlyCharges > (
      SELECT AVG(MonthlyCharges)
      FROM customer_churn_clean
  )
ORDER BY MonthlyCharges DESC;

-- Find customers whose tenure is below the overall average

SELECT
    customerID,
    tenure,
    Contract,
    Churn
FROM customer_churn_clean
WHERE tenure < (
    SELECT AVG(tenure)
    FROM customer_churn_clean
)
ORDER BY tenure;

-- Compare each customer's MonthlyCharges with the average charge of their contract type

SELECT
    customerID,
    Contract,
    MonthlyCharges
FROM customer_churn_clean c
WHERE MonthlyCharges > (
    SELECT AVG(MonthlyCharges)
    FROM customer_churn_clean
    WHERE Contract = c.Contract
)
ORDER BY Contract, MonthlyCharges DESC;

-- Calculate churn rate using a Common Table Expression

WITH churn_summary AS (
    SELECT
        Churn,
        COUNT(*) AS customer_count
    FROM customer_churn_clean
    GROUP BY Churn
)
SELECT
    Churn,
    customer_count,
    ROUND(
        customer_count * 100.0 /
        (SELECT SUM(customer_count) FROM churn_summary),
        2
    ) AS percentage
FROM churn_summary;

-- Calculate total customers and churned customers for each contract

WITH contract_summary AS (
    SELECT
        Contract,
        COUNT(*) AS total_customers,
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers
    FROM customer_churn_clean
    GROUP BY Contract
)
SELECT
    Contract,
    total_customers,
    churned_customers,
    ROUND(
        churned_customers * 100.0 / total_customers,
        2
    ) AS churn_rate
FROM contract_summary
ORDER BY churn_rate DESC;

-- Identify customers with short tenure and high monthly charges

WITH customer_risk AS (
    SELECT
        customerID,
        tenure,
        MonthlyCharges,
        Churn
    FROM customer_churn_clean
    WHERE tenure < 12
      AND MonthlyCharges > 70
)
SELECT *
FROM customer_risk
WHERE Churn = 'Yes'
ORDER BY MonthlyCharges DESC;

-- Give each customer a unique row number

SELECT
    customerID,
    Contract,
    MonthlyCharges,
    ROW_NUMBER() OVER (ORDER BY MonthlyCharges DESC) AS row_num
FROM customer_churn_clean;

-- Rank customers by MonthlyCharges within each contract type

SELECT
    customerID,
    Contract,
    MonthlyCharges,
    ROW_NUMBER() OVER (
        PARTITION BY Contract
        ORDER BY MonthlyCharges DESC
    ) AS contract_rank
FROM customer_churn_clean;

-- Rank customers based on MonthlyCharges

SELECT
    customerID,
    MonthlyCharges,
    RANK() OVER (
        ORDER BY MonthlyCharges DESC
    ) AS charge_rank
FROM customer_churn_clean;

-- Show each customer's charge along with the overall average

SELECT
    customerID,
    MonthlyCharges,
    ROUND(
        AVG(MonthlyCharges) OVER (),
        2
    ) AS overall_avg_charge
FROM customer_churn_clean;

-- Compare each customer's MonthlyCharges with the previous customer's charge

SELECT
    customerID,
    MonthlyCharges,
    LAG(MonthlyCharges) OVER (
        ORDER BY MonthlyCharges
    ) AS previous_charge
FROM customer_churn_clean;

-- Calculate the difference between current and previous customer's charge
SELECT
    customerID,
    MonthlyCharges,
    LAG(MonthlyCharges) OVER (
        ORDER BY MonthlyCharges
    ) AS previous_charge,
    MonthlyCharges -
    LAG(MonthlyCharges) OVER (
        ORDER BY MonthlyCharges
    ) AS charge_difference
FROM customer_churn_clean;

-- Compare each customer's charge with the next customer's charge

SELECT
    customerID,
    MonthlyCharges,
    LEAD(MonthlyCharges) OVER (
        ORDER BY MonthlyCharges
    ) AS next_charge
FROM customer_churn_clean;

-- Rank churned customers by their MonthlyCharges

SELECT
    customerID,
    Contract,
    MonthlyCharges,
    tenure,
    RANK() OVER (
        ORDER BY MonthlyCharges DESC
    ) AS charge_rank
FROM customer_churn_clean
WHERE Churn = 'Yes';

-- Create a customer master table

CREATE TABLE customers AS
SELECT
    customerID,
    gender,
    SeniorCitizen,
    Partner,
    Dependents
FROM customer_churn_clean;

select * from Customers limit 10;
SELECT COUNT(*) AS total_customers
FROM customers;

-- Create a table containing customer subscription details

CREATE TABLE subscriptions AS
SELECT
    customerID,
    tenure,
    Contract,
    PhoneService,
    MultipleLines,
    InternetService,
    Churn
FROM customer_churn_clean;

SELECT *
FROM subscriptions
LIMIT 10;

-- Create a table containing customer service usage

CREATE TABLE services AS
SELECT
    customerID,
    OnlineSecurity,
    OnlineBackup,
    DeviceProtection,
    TechSupport,
    StreamingTV,
    StreamingMovies
FROM customer_churn_clean;

SELECT *
FROM services
LIMIT 10;

-- Create a table containing customer payment information

CREATE TABLE payments AS
SELECT
    customerID,
    PaperlessBilling,
    PaymentMethod,
    MonthlyCharges,
    TotalCharges
FROM customer_churn_clean;

SELECT *
FROM payments
LIMIT 10;


SELECT *
FROM subscriptions
LIMIT 10;

SELECT COUNT(*) AS total_rows
FROM subscriptions;


DESCRIBE customers;

ALTER TABLE customers
MODIFY customerID VARCHAR(20) NOT NULL;

ALTER TABLE subscriptions
MODIFY COLUMN customerID VARCHAR(20) NOT NULL;

ALTER TABLE services
MODIFY COLUMN customerID VARCHAR(20) NOT NULL;

ALTER TABLE payments
MODIFY COLUMN customerID VARCHAR(20) NOT NULL;

ALTER TABLE subscriptions
ADD CONSTRAINT fk_subscriptions_customer
FOREIGN KEY (customerID)
REFERENCES customers(customerID);

ALTER TABLE services
ADD CONSTRAINT fk_services_customer
FOREIGN KEY (customerID)
REFERENCES customers(customerID);

ALTER TABLE payments
ADD CONSTRAINT fk_payments_customer
FOREIGN KEY (customerID)
REFERENCES customers(customerID);

--  Customers aur subscriptions ka matching data combine karna

SELECT
    c.customerID,
    c.gender,
    c.SeniorCitizen,
    s.Contract,
    s.tenure,
    s.Churn
FROM customers c
INNER JOIN subscriptions s
    ON c.customerID = s.customerID
LIMIT 10;

-- Combine customers with their payment information

SELECT
    c.customerID,
    c.gender,
    p.MonthlyCharges,
    p.PaymentMethod
FROM customers c
LEFT JOIN payments p
    ON c.customerID = p.customerID
LIMIT 10;

-- Combine customer, subscription, service, and payment data

SELECT
    c.customerID,
    c.gender,
    sub.Contract,
    sub.tenure,
    sub.InternetService,
    sub.Churn,
    ser.OnlineSecurity,
    ser.TechSupport,
    p.MonthlyCharges,
    p.PaymentMethod
FROM customers c
LEFT JOIN subscriptions sub
    ON c.customerID = sub.customerID
LEFT JOIN services ser
    ON c.customerID = ser.customerID
LEFT JOIN payments p
    ON c.customerID = p.customerID
LIMIT 10;

-- Find churned customers with their contract and payment details

SELECT
    c.customerID,
    c.gender,
    sub.Contract,
    sub.tenure,
    sub.Churn,
    p.MonthlyCharges,
    p.PaymentMethod
FROM customers c
JOIN subscriptions sub
    ON c.customerID = sub.customerID
JOIN payments p
    ON c.customerID = p.customerID
WHERE sub.Churn = 'Yes'
ORDER BY p.MonthlyCharges DESC;

-- Analyze churn by contract type using JOIN

SELECT
    sub.Contract,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN sub.Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        SUM(CASE WHEN sub.Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*),
        2
    ) AS churn_rate
FROM customers c
JOIN subscriptions sub
    ON c.customerID = sub.customerID
GROUP BY sub.Contract
ORDER BY churn_rate DESC;

-- Find high-churn contract types

SELECT
    sub.Contract,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN sub.Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        SUM(CASE WHEN sub.Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*),
        2
    ) AS churn_rate
FROM customers c
JOIN subscriptions sub
    ON c.customerID = sub.customerID
GROUP BY sub.Contract
HAVING churn_rate > 20
ORDER BY churn_rate DESC;

-- Analyze churn by payment method

SELECT
    p.PaymentMethod,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN sub.Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        SUM(CASE WHEN sub.Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*),
        2
    ) AS churn_rate
FROM customers c
JOIN subscriptions sub
    ON c.customerID = sub.customerID
JOIN payments p
    ON c.customerID = p.customerID
GROUP BY p.PaymentMethod
ORDER BY churn_rate DESC;

-- Analyze churn for customers with Online Security and Tech Support

SELECT
    ser.OnlineSecurity,
    ser.TechSupport,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN sub.Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        SUM(CASE WHEN sub.Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*),
        2
    ) AS churn_rate
FROM customers c
JOIN subscriptions sub
    ON c.customerID = sub.customerID
JOIN services ser
    ON c.customerID = ser.customerID
GROUP BY
    ser.OnlineSecurity,
    ser.TechSupport
ORDER BY churn_rate DESC;

-- Find payment methods with more than 500 customers

SELECT
    p.PaymentMethod,
    COUNT(*) AS customer_count,
    ROUND(AVG(p.MonthlyCharges), 2) AS avg_monthly_charge
FROM customers c
JOIN payments p
    ON c.customerID = p.customerID
GROUP BY p.PaymentMethod
HAVING COUNT(*) > 500
ORDER BY customer_count DESC;

--  Create a reusable customer churn analysis view

CREATE VIEW customer_churn_view AS
SELECT
    c.customerID,
    c.gender,
    c.SeniorCitizen,
    c.Partner,
    c.Dependents,
    sub.tenure,
    sub.Contract,
    sub.InternetService,
    sub.Churn,
    ser.OnlineSecurity,
    ser.OnlineBackup,
    ser.DeviceProtection,
    ser.TechSupport,
    p.PaperlessBilling,
    p.PaymentMethod,
    p.MonthlyCharges,
    p.TotalCharges
FROM customers c
LEFT JOIN subscriptions sub
    ON c.customerID = sub.customerID
LEFT JOIN services ser
    ON c.customerID = ser.customerID
LEFT JOIN payments p
    ON c.customerID = p.customerID;
    
--  View the combined customer churn data

SELECT *
FROM customer_churn_view
LIMIT 10;

-- Calculate churn rate by contract from the view

SELECT
    Contract,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*),
        2
    ) AS churn_rate
FROM customer_churn_view
GROUP BY Contract
ORDER BY churn_rate DESC;

-- Modify the existing customer churn view

CREATE OR REPLACE VIEW customer_churn_view AS
SELECT
    c.customerID,
    c.gender,
    sub.Contract,
    sub.tenure,
    sub.Churn,
    p.MonthlyCharges,
    p.PaymentMethod
FROM customers c
LEFT JOIN subscriptions sub
    ON c.customerID = sub.customerID
LEFT JOIN payments p
    ON c.customerID = p.customerID;

-- Check existing indexes on customers

SHOW INDEX FROM customers;


-- Convert indexed columns from TEXT to VARCHAR

ALTER TABLE payments
MODIFY COLUMN PaymentMethod VARCHAR(50) NOT NULL;

ALTER TABLE subscriptions
MODIFY COLUMN Contract VARCHAR(50) NOT NULL;

ALTER TABLE subscriptions
MODIFY COLUMN Churn VARCHAR(10) NOT NULL;

-- Create indexes for frequently analyzed columns

CREATE INDEX idx_payment_method
ON payments(PaymentMethod);

CREATE INDEX idx_contract
ON subscriptions(Contract);

CREATE INDEX idx_churn
ON subscriptions(Churn);

-- Calculate overall customer churn rate

SELECT
    COUNT(*) AS total_customers,
    SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*),
        2
    ) AS churn_rate
FROM customer_churn_clean;

--  Analyze churn rate by contract type

SELECT
    Contract,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*),
        2
    ) AS churn_rate
FROM customer_churn_clean
GROUP BY Contract
ORDER BY churn_rate DESC;

-- Analyze churn by customer tenure groups

SELECT
    CASE
        WHEN tenure <= 12 THEN '0-12 Months'
        WHEN tenure <= 24 THEN '13-24 Months'
        WHEN tenure <= 48 THEN '25-48 Months'
        ELSE '49+ Months'
    END AS tenure_group,

    COUNT(*) AS total_customers,

    SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,

    ROUND(
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*),
        2
    ) AS churn_rate

FROM customer_churn_clean
GROUP BY tenure_group
ORDER BY churn_rate DESC;

-- Analyze churn by monthly charge groups

SELECT
    CASE
        WHEN MonthlyCharges < 40 THEN 'Low Charges'
        WHEN MonthlyCharges < 80 THEN 'Medium Charges'
        ELSE 'High Charges'
    END AS charge_group,

    COUNT(*) AS total_customers,

    SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,

    ROUND(
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*),
        2
    ) AS churn_rate

FROM customer_churn_clean
GROUP BY charge_group
ORDER BY churn_rate DESC;

-- Analyze churn by internet service

SELECT
    InternetService,
    COUNT(*) AS total_customers,

    SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,

    ROUND(
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*),
        2
    ) AS churn_rate

FROM customer_churn_clean
GROUP BY InternetService
ORDER BY churn_rate DESC;

-- Analyze churn by payment method

SELECT
    PaymentMethod,
    COUNT(*) AS total_customers,

    SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,

    ROUND(
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*),
        2
    ) AS churn_rate

FROM customer_churn_clean
GROUP BY PaymentMethod
ORDER BY churn_rate DESC;

-- Identify high-risk churned customers

SELECT
    customerID,
    tenure,
    Contract,
    MonthlyCharges,
    InternetService,
    PaymentMethod,
    Churn
FROM customer_churn_clean
WHERE tenure <= 12
  AND MonthlyCharges > 70
  AND Churn = 'Yes'
ORDER BY MonthlyCharges DESC;

-- Calculate total charges from churned customers

SELECT
    ROUND(SUM(TotalCharges), 2) AS churned_customer_total_charges
FROM customer_churn_clean
WHERE Churn = 'Yes';

-- Compare charges between churned and retained customers

SELECT
    Churn,
    COUNT(*) AS customer_count,
    ROUND(AVG(MonthlyCharges), 2) AS avg_monthly_charges,
    ROUND(AVG(TotalCharges), 2) AS avg_total_charges
FROM customer_churn_clean
GROUP BY Churn
ORDER BY Churn;

-- Generate executive-level churn KPIs

SELECT
    COUNT(*) AS total_customers,

    SUM(CASE
        WHEN Churn = 'Yes' THEN 1
        ELSE 0
    END) AS churned_customers,

    SUM(CASE
        WHEN Churn = 'No' THEN 1
        ELSE 0
    END) AS retained_customers,

    ROUND(
        SUM(CASE
            WHEN Churn = 'Yes' THEN 1
            ELSE 0
        END) * 100.0 / COUNT(*),
        2
    ) AS churn_rate,

    ROUND(AVG(MonthlyCharges), 2) AS avg_monthly_charges,

    ROUND(SUM(MonthlyCharges), 2) AS total_monthly_revenue

FROM customer_churn_clean;












































